# METADATA
site_name: 'Waterbot Documentations'

# SITE NAVIGATIONS
nav:
  - Home: 'index.md'
  # Command Docs
  - Core:
      - 'Home': 'commands/core/index.md'
      - 'Activity': 'commands/core/activity.md'
      - 'Say': 'commands/core/say.md'
  - Developers:
      - 'Home': 'commands/devs/index.md'

  - Fun:
      - 'Home': 'commands/fun/index.md'

  - GuildConfig:
      - 'Home': 'commands/guild/index.md'

  - Moderation:
      - 'Home': 'commands/mod/index.md'

  - Utilities:
      - 'Home': 'commands/utils/index.md'

  # Guides
  - Guides:
      - 'Home': 'guides/index.md'
      - 'Setting up': 'guides/setup.md'
      - 'Selfhosting': 'guides/selfhosting.md'

  # About page
  - About: 'about.md'

# THEME ITEMS
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  logo: 'images/icon.ico'
  language: 'en'
  feature:
    tabs: true

#EXTRA SOCIAL LINKS
extra:
  social:
    - type: 'github'
      link: 'https://github.com/waterbotdev'
    - type: 'twitter'
      link: 'https://twitter.com/waterbotdev'

# REPO FOR TOP RIGHT DISPLAY
repo_name: 'wdev/docs'
repo_url: 'https://github.com/waterbotdev/docs'

# Useful extentions
markdown_extensions:
  - meta
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.tasklist:
      clickable_checkbox: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true