site_name: 'Waterbot Documentations'

nav:
  - Home: index.md
  - About: about.md

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  logo: 'images/icon.ico'
  language: 'en'

repo-name: 'waterbotdev/docs'
repo-url: 'https://github.com/waterbotdev/docs'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/waterbotdev'
    - type: 'twitter'
      link: 'https://twitter.com/waterbotdev'

# Useful extentions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true