name: BuildSite

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build site
      run: mkdocs build

    - name: Move site files to temp
      run: mv site/ ../

    #- name: Checkout gh-pages branch
    #  run: git checkout gh-pages

    - name: Kill the fire
      run: rm * -vfr

    - name: Move site back
      run: mv ../site/* ./

    - name: Basic git stuff
      run: |
        git config user.name "GitHub Actions"
        git config user.email "chuenghowui@gmail.com"
        git commit -m "Auto build site"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: 'gh-pages'
        # directory: '/home/runner/work/docs/docs/site'
        force: true
